# Generated by Django 4.1.2 on 2022-10-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('ratingOfHome', models.IntegerField()),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='LandLords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ratingOfLord', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['LastName', 'FirstName'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsOfLandLords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReview', models.DateField()),
                ('textOfReview', models.CharField(max_length=500)),
                ('typingReview', models.TextField()),
                ('reviewOfLord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='create_review.landlords')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsOfHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReview', models.DateField()),
                ('textOfReview', models.CharField(max_length=500)),
                ('typingReview', models.TextField()),
                ('reviewOfLord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='create_review.home')),
            ],
        ),
        migrations.CreateModel(
            name='photosForReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePhotos', models.DateField()),
                ('Review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='create_review.home')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='reviewOfHome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='create_review.landlords'),
        ),
    ]
